ryota-ka/twterm

- timeline.rb
現状 j / k キーなどで画面を更新しないとマーカーが付かないので。
> Fav / RT の表示を非同期に更新する

- status.rb
- timeline.rb
まず、タイムゾーンの設定をきちんとする。
(今回は UTC+0900 決め打ちで、別イシューで対応してもいいかも。)
直近24時間以内の投稿であれば、時刻のみを表示する。
それ以前であれば、日付と時刻を表示する。
> ツイートの投稿時間の表示を改善する

- client.rb
誰かが自分のツイートをふぁぼったときだけでなく、自分が誰かのツイートをふぁぼった時にもイベントが発生するらしい。
> ふぁぼ通知がおかしい

- lib/twterm/auth.rb
`Launchy::CommandNotFoundError` を rescue する。
> ブラウザがない環境では認証用の URL を表示するようにする

- lib/twterm/tab/new/list.rb
新規タブでリストを選択するときにリスト名でソートされていると選びやすい.
なんらかの形でインクリメンタルサーチができるとなお良い.
> リストをアルファベット順にソートしてほしい

- lib/twterm/notification/base.rb
> ふぁぼ通知などの際に HTML がエスケープされて表示されている

- twterm.gemspec
`Array#to_h` を使っているので Ruby 2.1 以上じゃないと動かない。
> Ruby の required version を書く

- lib/twterm/tab/statuses_tab.rb
> 新規タブを開く機能のキーボードショートカットが表示されていない

- lib/twterm/tweetbox.rb
`EmptyTextError` を rescue していない。
> 新規ツイート時にテキストが空だと落ちる

- lib/twterm/tab/statuses_tab.rb
grep 時、画面下部にクエリが表示されたままになっているので、クリアしてあげる。
#170 までの一時しのぎ。
> 画面上に表示されている grep のクエリをクリアする

- lib/twterm/tab/key_assignments_cheatsheet.rb
> Tab::KeyAssignmentsCheatsheet をスクロール可能にする

- lib/twterm/history/base.rb
開発時に2プロセス立ち上げていると、問題が生じることが多い。
この際なので直しておく。
> screen_name や hashtag の読み込みに失敗したときに落ちる

- lib/twterm/tab/statuses/user_timeline.rb
- lib/twterm/tab/user_tab.rb
`#==` メソッドを適切に定義してやることで、重複して開かれることを防ぐ。
> Tab::UserTab や Tab::Statuses::UserTimeline が同一のものでも複数開かれるのを防ぐ

- lib/twterm/tab/base.rb
- lib/twterm/tab/users/base.rb
`Tab::Users::Base#update` で実装したように、スペースを表示しておくと、文字がズレなくなるっぽい。
> 特殊な文字が現れた際にも表示がズレないように、透明のスペースを表示しておく

- lib/twterm/tab/base.rb
- lib/twterm/tab/new/list.rb
- lib/twterm/tab/new/search.rb
- lib/twterm/tab/new/start.rb
- lib/twterm/tab/new/user.rb
- lib/twterm/tab/statuses/conversation.rb
- lib/twterm/tab/statuses/home.rb
- lib/twterm/tab/statuses/list_timeline.rb
- lib/twterm/tab/statuses/mentions.rb
- lib/twterm/tab/user_tab.rb
ユーザータブなどは、ユーザー ID を受け取ってから、非同期でユーザーを取得しているが、
ユーザーの取得が完了した際にタイトルを書き換えても、画面が更新されない。
`Tab::Base#title=` というメソッドを設けて、これが呼ばれた際に、 `TabManager` の画面更新処理を行うようにする。
> タブのタイトルが変更されたときに画面を更新する

- lib/twterm/client.rb
`count` の値は [Twitter Gem のドキュメント](http://www.rubydoc.info/gems/twitter/Twitter%2FREST%2FFavorites%3Afavorites) には100件までと書いていたが、
[Twitter API のリファレンス](https://dev.twitter.com/rest/reference/get/favorites/list)には200件まで取得できると書いていた。
`statuses/home_timeline` とか `statuses/mentions_timeline` も200件まで取得できるらしいので、
合わせて変更しても良さそう。
> Client#favorites の取得件数を200件にする

- lib/twterm/tab/statuses/base.rb
`Launchy::CommandNotFoundError` を `rescue` してあげたい。
> ブラウザがない環境で Tab::Statuses::Base#open_link を実行すると落ちる

- lib/twterm/screen.rb
> 画面リサイズ時に現在表示されているタブしかリサイズされない

- lib/twterm/app.rb
- lib/twterm/screen.rb
#33 で実装したけどなんかうまく動かないことが多い気がする．
(SIGWINCH を trap できていない？)
なので，1分間に1回ほど `Screen#resize` を呼び出してあげる．
(あまり頻繁すぎても描画コストが無駄にかかるし，通知が消えてしまったりするので．)
> 画面のリサイズを定期的に行うようにする

- lib/twterm/streaming_client.rb
This pull request will fix an issue where tweet bodies won't be displayed in favorite notifications (#260).
It was just because of my misunderstanding about the specification of Twitter's Streaming API (target tweet of a favorite event can be accessed with `target_object` key, not `target` key.)
> Modify key name from target to target_object

- lib/twterm/extensions/enumerator/lazy.rb
- lib/twterm/tab/direct_message/conversation.rb
- lib/twterm/tab/statuses/base.rb
- spec/twterm/extension/enumerator/lazy_spec.rb
Fixed a bug where `Enumrator::Lazy#scan` won't yield the initial value passed as an argument.
(It's a shame I haven't been noticed such a trivial issue!)
Also fixed `#drawable_item_count` calculations depending on the method.
> Fix definition of Enumrator::Lazy#scan

- lib/twterm/filter_query_window.rb
Fix a performance issue where non-blocking reads causes an infinite loop.
I've been misunderstood the behaviour of `Curses#timeout=`
Solved by passing a negative number so that it would use blocking read.
> Fix a performance issue caused by non-blocking read

- lib/twterm/tab/scrollable.rb
have been forgotten to subtract 1!
this will fix an issue where search target item sometimes does not shows up on the screen when called `find_next` or `find_previous`.
> Fix definition of Tab::Scrollable::Scroller#nth_item_drawable?

- lib/twterm/user.rb
Assign empty string instead of a `Twitter::NullObject` to `@description` inside `User` class when blank.
This will fix an issue where user tabs won't be rendered when description is empty.
> Ensure User#description returns a String

- Gemfile.lock
- twterm.gemspec
Updated [flori/json](https://github.com/flori/json) to v2.0.2 so that we can build it on Ruby 2.4, where `Fixnum` and `Bignum` is simply unified into `Integer` class.
> Update json to v2.0.2

- .travis.yml
Ruby 2.4 has been released and it must be supported :christmas_tree: :gift: :santa:
> Test against Ruby 2.4

- Gemfile.lock
- twterm.gemspec
Reverting #282
I've noticed that twitter v6.0.0 no longer depends on json gem since this commit: https://github.com/sferik/twitter/commit/27980f45fb357e34b86e46cb9134d86ed29b3ce3
So this pull request seems to be unnecessary.
> Revert "Update json to v2.0.2"

- Gemfile.lock
- twterm.gemspec
twitter-text v1.14.3 includes an issue (https://github.com/twitter/twitter-text/issues/162) where a file does not exist and it cannot be run.
Resolving the problem by fixing its version.
> Fix version of twitter-text to 1.14.0

- lib/twterm/tab/searchable.rb
On Ruby 2.4, we get warnings as `Tab::Searchable#search_query` is delegated to `Tab::Searchable::Scroller#search_query`, which is a private method.
Suppressed them by making the method public.
> Suppress warning caused by delegating to private method

- lib/twterm/tab/searchable.rb
Fixed a bug where search query input mode cannot be cancelled with ^C or backspace.
> Return empty query when input is cancelled

- lib/twterm/image/string_image.rb
Pre-concatenate two strings when appending two `StringImage`'s, instead of rendering them separately.
> Preconcat string images

- lib/twterm/tab/dumpable.rb
Completed missing comma. This seems to have been causing `NoMethodError`.
> Complete missing comma

- lib/twterm/key_mapper.rb
- lib/twterm/key_mapper/abstract_key_mapper.rb
- lib/twterm/key_mapper/no_such_command.rb
- lib/twterm/key_mapper/no_such_key.rb
- lib/twterm/tab/direct_message/conversation.rb
- lib/twterm/tab/direct_message/conversation_list.rb
This pull request makes the app handle key mapper errors more carefully, introducing more object-oriented `KeyMapper::NoSuchCommand` and `KeyMapper::NoSuchKey` error classes.
`TOML::ValueOverwriteError` will be also rescued even if the key configurations file is ill-formatted.
> Handle key mapper errors more carefully

- lib/twterm/notifier.rb
Fixed a `LocalJumpError` which has been caused by calling `break` inside a block.
> Fix LocalJumpError

- lib/twterm/streaming_client.rb
Rescues `Errno::ETIMEDOUT` which can be raised within establishing a new connection for the user streams.
> Rescue Errno::ETIMEDOUT

- lib/twterm/repository/abstract_entity_repository.rb
- lib/twterm/repository/abstract_expirable_entity_repository.rb
- lib/twterm/repository/friendship_repository.rb
- lib/twterm/tab/new/search.rb
- lib/twterm/tab/statuses/base.rb
- lib/twterm/tab/user_list_management.rb
- lib/twterm/tab/users/base.rb
Replaced mutable data structures such as `Array` or `Hash` which can be referenced from multiple threads with thread-safe ones (e.g. `Concurrent::Array`, `Concurrent::Hash`, provided by concurrent-ruby), in order to avoid data races.
> Pay more attention to thread safety

- lib/twterm/app.rb
Supported screen resizing which was mistakenly removed in 00e94f95781ad8dd10cf5a21e4e63f3644e7f96d again.
> Support screen resizing again

- lib/twterm/tab/statuses/base.rb
Fixed status height calculation to avoid text overflow.
> Fix text overflow

- Gemfile.lock
- README.md
- lib/twterm/version.rb
- twterm.gemspec
Updated readme, description, required Ruby version, and bumped version to v2.0.0.beta1.
> Prepare for v2

- lib/twterm/key_mapper/status_key_mapper.rb
Changed default key assignment for `status.like` from `L` to `F`, as it has been overlapped with `cursor.move_to_bottom`.
> Change default key assignment for status.like to F

- lib/twterm/tab/users/base.rb
Colored `[protected]` badges with yellow, and `[verified]` badges in cyan, as in individual user tab.
> Add color to [protected] and [verified] badges in users tab

- Gemfile.lock
- lib/twterm/version.rb
Bumped version to v2.0.0.beta, including colored badges in user tabs and changed default key assignment.
> Bump version to v2.0.0.beta2

- lib/twterm/tab/base.rb
- lib/twterm/tab/statuses/base.rb
- lib/twterm/tab/statuses/conversation.rb
- lib/twterm/tab/statuses/favorites.rb
- lib/twterm/tab/statuses/home.rb
- lib/twterm/tab/statuses/list_timeline.rb
- lib/twterm/tab/statuses/mentions.rb
- lib/twterm/tab/statuses/search.rb
- lib/twterm/tab/statuses/user_timeline.rb
Clarified responsibilities between `#fetch` and `#reload` methods on status tab classes, which has been quite vague.
- `#fetch` method 
- now focusing on obtain statuses from the server
- does nothing except above
- returns a promise of fetched statuses
- `#reload` method
- obtains statuses via `#fetch`
- sorts statuses in the tab
- re-renders the screen
- now can be commonly defined in the superclass (`Tab::Statuses::Base`)
And `tab.reload` now invokes `#reload` method.
> Clarify responsibilities between #fetch and #reload

- lib/twterm/rest_client.rb
- lib/twterm/tab/statuses/list_timeline.rb
Modified the definition of `Tab::Statuses::ListTimeline#==` to compare their list ids, instead of lists themselves. This should fix the problem where the list tabs won't be restored correctly.
> Modify identity determination of Tab::Statuses::ListTimeline

- lib/twterm/image.rb
Use `*` instead of `x` to render checkmarks.
> Update design for checkbox image

- lib/twterm/tab/base.rb
- lib/twterm/tab/statuses/base.rb
Defined `#reload` method in `Tab::Statuses::Base`, not in `Tab::Base`.
> Define #reload in proper class

- lib/twterm/tab/statuses/conversation.rb
Fixed `NameError` caused by referencing `status`.
This should fix the problem where multiple conversation tab cannot be opened at the same time.
(@morishin thank you for telling me about the problem :wink:)
> Modify definition of Tab::Statuses::Conversation#==

- lib/twterm/key_mapper.rb
- lib/twterm/key_mapper/abstract_key_mapper.rb
Automatically add missing commands to `~/.twterm/keys.toml` when launched. This enables us to safely add a new command in the future.
> Complete missing commands

- lib/twterm/streaming_client.rb
Retweets should not be considered as mentions.
> Exclude retweets from mentions

- lib/twterm/tab_manager.rb
Fixed a bug where the app crashes when trying to close `Home` or `Mentions` tab.
> Remove excessive argument

- .circleci/config.yml
- README.md
Dropped support for Ruby <2.4, which have reached their EoL.
> Drop support for Ruby <2.4

- .circleci/config.yml
- README.md
- twterm.gemspec
As [Ruby 2.4 has reached its EOL this March](https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/), we'll drop the support for it.
> Drop support for Ruby 2.4

- bin/twterm
Ruby versions older than v2.5.0 is no longer supported
> Remove unnecessary condition branching

- README.md
Updated "installation" section in README; `twterm` can now be installed via Homebrew.
[Rendered](https://github.com/ryota-ka/twterm/blob/990705561681d6885201fba67b8a38c185fccbbd/README.md#installation)
The tap is available here: https://github.com/ryota-ka/homebrew-twterm
> Note about installation via Homebrew

- lib/twterm/tab/statuses/abstract_statuses_tab.rb
Delegations to private methods cause warnings.
https://bugs.ruby-lang.org/issues/12782
> Publish AbstractStatusTab#search_query_window

- lib/twterm/screen.rb
It has been misplaced at the same position as the search query window.
> Place message window to the right position
