extentions.rb
screen.rb
status.rb
timeline.rb

ツイート全体を反転させるのではなく、ツイートの左側の色を変更する。

ツイートのハイライト方法を変更する

---

client.rb
screen.rb
status.rb
timeline.rb

リツイート機能の実装

---

app.rb
screen.rb
tweetbox.rb

ツイート作成時に C-c を押してもアプリケーションが終了してしまう

---

app.rb
client.rb
screen.rb
tab/base.rb
tab/mentions_tab.rb
tab/status_tab.rb
tab/timeline.rb
tab_manager.rb

Multiple tabs

---

status.rb
tab/statuses_tab.rb

リツイート表示の変更

---

client.rb
tab/user_tab.rb

ユーザータイムラインが20件しか読み込まれない

---

status.rb
tab/statuses_tab.rb

リツイートに関しては、オリジナルの時刻ではなく、リツイートされた時刻を以ってソートしたい。

ツイートソート時のリツイートの時刻

---

tab/new/search.rb
tweetbox.rb

Curses を再度開く時にバグることがある

---

lib/twterm.rb
lib/twterm/version.rb

バージョン 1.0.2 に上げる

---

lib/twterm/version.rb

バージョン 1.0.3

---

lib/twterm.rb
lib/twterm/tweetbox.rb
twterm.gemspec

140字を超えた時の対応

---

lib/twterm/tab/statuses_tab.rb

Tab::AutoReloadable を include しているのを削除する

---

lib/twterm/screen.rb
lib/twterm/status.rb
lib/twterm/tab/new/list.rb
lib/twterm/tab/statuses_tab.rb

`/` に続いてクエリを入力した際に、タブ内のツイートのうちマッチするもののみ表示するようにする。

タブ内のテキスト検索

---

lib/twterm/notifier.rb
lib/twterm/tab/statuses_tab.rb

`?` キーでキーボードショートカットの一覧を表示できるようにした(#94)ので、help が不要になった。

画面下部の help を消す

---

lib/twterm/tab/new/start.rb

間違って add してたっぽい。次のリリースにはまだ含めないです。

Tab::New::Start から Tab::TrackTab を呼べるようになっている

---

Gemfile.lock
lib/twterm.rb
lib/twterm/filter_query_window.rb
lib/twterm/filterable_list.rb
lib/twterm/version.rb

こんな時間まで起きてるんだったらさっきバージョン上げなければよかった。

バージョン 1.0.12

---

lib/twterm/tab/key_assignments_cheatsheet.rb
lib/twterm/tab_manager.rb

ショートカットキーで自分のプロフィールを表示できるようにする

---

lib/twterm/promise.rb

トップレベルの `::Promise` という風になってしまっているが、
`Twterm` モジュールの中に入れてやる。

Promise class が属する namespace がおかしい

---

lib/twterm/tab/scrollable.rb

タイムラインに新規ツイートがきた場合のオートスクロール

---

lib/twterm/tab/key_assignments_cheatsheet.rb
lib/twterm/tab/scrollable.rb

key assignments cheatsheet に conversation tab が記載されていない

---

lib/twterm/app.rb
lib/twterm/auth.rb
lib/twterm/config.rb

エラーメッセージは "Failed to send request: Rate limit exceeded" で, ずっと Loading のままでした。
通信はしてるみたいですが。

Key assignments で My profile が表示できない

---

lib/twterm/client.rb

Search tab を三つ以上開けない

---

lib/twterm/tab/key_assignments_cheatsheet.rb

key assignments cheatsheet に，1-9 / 0 のキーバインドについて書く

---

Gemfile.lock
lib/twterm/version.rb

バージョン1.1.3

---

lib/twterm/tab/base.rb
lib/twterm/tab/statuses/base.rb

Unsubscribe events in Tab::Base#close

---

lib/twterm/client.rb
lib/twterm/direct_message.rb
lib/twterm/direct_message_composer.rb
lib/twterm/direct_message_manager.rb
lib/twterm/event/direct_message/fetched.rb
lib/twterm/rest_client.rb
lib/twterm/tab/direct_message/conversation.rb
lib/twterm/tab/direct_message/conversation_list.rb
lib/twterm/tab/new/start.rb
lib/twterm/tab/user_tab.rb

- Added tabs
- `Tab::DirectMessage::ConversationList`
- `Tab::DirectMessage::Conversation`
- Enabled to send direct messages via
- `Tab::DirectMessage::ConversationList`
- `Tab::DirectMessage::Conversation`
- `Tab::UserTab`
implements #186

Enable to receive / send direct messages

---

lib/twterm/tab/statuses/search.rb

Fix a bug where statuses in search tabs are not sorted

---

lib/twterm/filter_query_window.rb

Fix a performance issue caused by non-blocking read

---

lib/twterm/rest_client.rb
lib/twterm/tab/user_tab.rb

fixed friendship behavior
- fix an issue where "follows you" label shows up even if the user does not follow the current user
- rerender the tab after looking up friendship

Fix friendship

---

lib/twterm/image.rb
lib/twterm/rest_client.rb
lib/twterm/tab/user_list_management.rb
lib/twterm/tab/user_tab.rb

Implemented `Tab::UserListManagement`, which enables us to add user to and/or remove them from owned lists.

Add Tab::UserListManagement

---

lib/twterm/tab/direct_message/conversation.rb
lib/twterm/tab/direct_message/conversation_list.rb
lib/twterm/tab/loadable.rb
lib/twterm/tab/new/list.rb
lib/twterm/tab/new/search.rb
lib/twterm/tab/statuses/base.rb
lib/twterm/tab/statuses/favorites.rb
lib/twterm/tab/statuses/home.rb
lib/twterm/tab/statuses/list_timeline.rb
lib/twterm/tab/statuses/mentions.rb
lib/twterm/tab/statuses/search.rb
lib/twterm/tab/statuses/user_timeline.rb
lib/twterm/tab/user_list_management.rb
lib/twterm/tab/users/base.rb
lib/twterm/tab/users/followers.rb
lib/twterm/tab/users/friends.rb

Added `Tab::Loadable` module, which manages the state for initial data loading.
This module allows various tabs to realize and modify their loading state easily and tell it to the user.

Display loading state

---

lib/twterm/tab/statuses/conversation.rb

Fix a LocalJumpError caused by return statement in a block

---

lib/twterm/image.rb
lib/twterm/image/brackets.rb
lib/twterm/image/parens.rb
lib/twterm/key_mapper.rb
lib/twterm/key_mapper/app_key_mapper.rb
lib/twterm/key_mapper/cursor_key_mapper.rb
lib/twterm/key_mapper/general_key_mapper.rb
lib/twterm/key_mapper/status_key_mapper.rb
lib/twterm/key_mapper/tab_key_mapper.rb
lib/twterm/tab/base.rb
lib/twterm/tab/key_assignments_cheatsheet.rb
lib/twterm/tab/searchable.rb
lib/twterm/tab_manager.rb

Always use `require` instead of `require_relative`.

Use absolute path to require files instead of using require_relative

---

spec/spec_helper.rb
spec/supports/shared_examples/abstract_key_mapper.rb
spec/twterm/key_mapper/app_key_mapper_spec.rb
spec/twterm/key_mapper/status_key_mapper_spec.rb
spec/twterm/key_mapper/tab_key_mapper_spec.rb

Configured to load files under `spec/supports/` directory automatically.

Load files under spec/supports/ automatically

---

Gemfile.lock
lib/twterm/status.rb
lib/twterm/user.rb
spec/fixtures/status.json
spec/fixtures/user.json
spec/spec_helper.rb
spec/twterm/status_spec.rb
spec/twterm/user_spec.rb
twterm.gemspec

Added some simple unit tests for `Status` and `User` classes.
They are now unit-testable thanks to #305!

Introduce simple unit tests for entities

---

lib/twterm/image.rb
lib/twterm/image/between.rb
lib/twterm/rest_client.rb
lib/twterm/tab/new/start.rb
lib/twterm/tab/rate_limit_status.rb
lib/twterm/tab/scrollable.rb

Added `Tab::RateLimitStatus`, which shows rate limiting status for all GET requests.
[![Screenshot from Gyazo](https://gyazo.com/25b489ce1c6df0f0f24b0cf069091962/raw)](https://gyazo.com/25b489ce1c6df0f0f24b0cf069091962)

Add Tab::RateLimitStatus

---

lib/twterm/tab/scrollable.rb
lib/twterm/tab/statuses/base.rb
lib/twterm/tab/statuses/favorites.rb
lib/twterm/tab/statuses/home.rb
lib/twterm/tab/statuses/list_timeline.rb
lib/twterm/tab/statuses/mentions.rb
lib/twterm/tab/statuses/user_timeline.rb

Refined behavior of sorting statuses within `Tab::Statuses::Base`.

Refine sorting

---

lib/twterm/repository/abstract_expirable_entity_repository.rb
lib/twterm/repository/status_repository.rb
lib/twterm/rest_client.rb
lib/twterm/status.rb
lib/twterm/tab/statuses/base.rb
spec/twterm/status_spec.rb

Unretweeting is now supported.

Support unretweet

---

lib/twterm/rest_client.rb

Fixed a bug where a replying status cannot be created due to a `NoMethodError`.

Fix a bug on making a reply

---

README.md

Noted that `^C` key is available for quitting the app.

Note that ^C is reserved for app.quit

---

lib/twterm/app.rb
lib/twterm/event/status_garbage_collected.rb
lib/twterm/event/user_garbage_collected.rb
lib/twterm/repository/abstract_expirable_entity_repository.rb
lib/twterm/repository/status_repository.rb
lib/twterm/repository/user_repository.rb
lib/twterm/tab/statuses/base.rb
lib/twterm/tab/users/base.rb

Publish events when garbage collected, which are subscribed by statuses tabs in order to delete the target statuses.

Publish events when garbage collected

---

Gemfile.lock
lib/twterm/version.rb

Bumped version to v2.0.0.beta3, with modification on making replies and improved garbage collection.

Bump version to v2.0.0.beta3

---

lib/twterm/rest_client.rb

Revive feedbacks after a direct message is sent that have been missing.

Revive feedbacks after a direct message is sent

---

Gemfile.lock
lib/twterm/version.rb

Bumped version to v2.0.0.beta4

Bump version to v2.0.0.beta4

---

lib/twterm/tab/new/search.rb

Load and update saved searches every time `Tab::New::Search` being initialized.

Load saved search every time

---

README.md

It appears to be more interactive.

Replace screenshot with screencast

---

lib/twterm/repository/abstract_expirable_entity_repository.rb
lib/twterm/repository/status_repository.rb
lib/twterm/repository/user_repository.rb
lib/twterm/tab/statuses/base.rb

Introduced enhanced lifecycle management on entities (statuses and users).

Introduce enhanced lifecycle management

---

Gemfile.lock
lib/twterm/version.rb

Bump version to v2.0.0

---

Gemfile.lock
lib/twterm/version.rb

Bump version to v2.0.1

---

lib/twterm/tab/statuses/conversation.rb

Fetch statuses that are possibly engaged in the conversation.

Fetch possible replies

---

lib/twterm/key_mapper/status_key_mapper.rb
lib/twterm/repository/status_repository.rb
lib/twterm/rest_client.rb
lib/twterm/status.rb
lib/twterm/tab/statuses/base.rb
lib/twterm/tab/statuses/conversation.rb
lib/twterm/tweetbox.rb

Supported quotes. Quoted statuses now appears in conversation tabs, and you also can quote a status via `Q` key.

Support quotes

---

lib/twterm/tab/statuses/cacheable.rb
lib/twterm/tab/statuses/conversation.rb
lib/twterm/tab/statuses/user_timeline.rb

Retrieve statuses from the cache if available.

Retrieve statuses from cache

---

Gemfile.lock
lib/twterm/version.rb

Releasing v2.1.0, including enhanced completion for search query, support for tweet quoting, and improved conversation tab.

Bump version to v2.1.0

---

.travis.yml
Gemfile.lock
lib/twterm/key_mapper/abstract_key_mapper.rb
lib/twterm/notifier.rb
lib/twterm/repository/abstract_expirable_entity_repository.rb
lib/twterm/rest_client.rb
lib/twterm/scheduler.rb
lib/twterm/search_query_window.rb
lib/twterm/streaming_client.rb
lib/twterm/tab/base.rb
lib/twterm/tab/new/list.rb
lib/twterm/tab/scrollable.rb
lib/twterm/tab/searchable.rb
lib/twterm/tab/user_tab.rb
lib/twterm/tab_manager.rb
twterm.gemspec

Introduced [RuboCop](https://github.com/bbatsov/rubocop) and suppressed all the warnings.

Introduce RuboCop

---

lib/twterm/persistable_configuration_proxy.rb

Fixed an issue where preferences could not be updated.

Return values with the same type in all cases

---

lib/twterm/streaming_client.rb

Fix a bug where timeline status events are not dispatched

---

Gemfile.lock
lib/twterm/version.rb

Bump version to v2.2.0

---

lib/twterm/app.rb
lib/twterm/completer/default_completer.rb
lib/twterm/completer/search_query_completer.rb
lib/twterm/hashtag.rb
lib/twterm/image_builder/user_name_image_builder.rb
lib/twterm/repository/hashtag_repository.rb
lib/twterm/status.rb
lib/twterm/tab/direct_message/conversation.rb
lib/twterm/tab/direct_message/conversation_list.rb
lib/twterm/tab/status_tab.rb
lib/twterm/tab/statuses/base.rb
lib/twterm/tab/user_tab.rb
lib/twterm/tab/users/base.rb
lib/twterm/user.rb
spec/twterm/image_builder/user_name_image_builder_spec.rb

Looks like this:
[![Screenshot from Gyazo](https://gyazo.com/13369b6948c141c2119aae4c71a565a4/raw)](https://gyazo.com/13369b6948c141c2119aae4c71a565a4)

Implement status tab

---

Gemfile.lock
twterm.gemspec

Added `yard` to dev deps to generate docs.

Add yard to development dependencies

---

lib/twterm/tab/statuses/base.rb

Implement #open_status_tab method in Tab::Statuses::Base class

---

Gemfile.lock
lib/twterm/version.rb

Bump version to v2.3.0

---

lib/twterm/rest_client.rb
lib/twterm/status.rb

Followed changes described in [Tweet updates](https://developer.twitter.com/en/docs/tweets/tweet-updates).

Support extended tweets

---

lib/twterm/app.rb
lib/twterm/direct_message_composer.rb
lib/twterm/environment.rb
lib/twterm/event/open_photo.rb
lib/twterm/event/screen/refresh.rb
lib/twterm/photo_viewer.rb
lib/twterm/photo_viewer_backend/abstract_photo_viewer_backend.rb
lib/twterm/photo_viewer_backend/browser_backend.rb
lib/twterm/photo_viewer_backend/imgcat_backend.rb
lib/twterm/photo_viewer_backend/quick_look_backend.rb
lib/twterm/preferences.rb
lib/twterm/screen.rb
lib/twterm/tab/new/search.rb
lib/twterm/tab/new/user.rb
lib/twterm/tab/preferences/index.rb
lib/twterm/tab/preferences/photo_viewer_backend.rb
lib/twterm/tab/status_tab.rb
lib/twterm/tweetbox.rb

Added photo viewer, closing #59.
Currently the following 3 backends are available.
- browser backend
- `imgcat` backend
- Quick Look backend

Add photo viewer

---

Gemfile.lock
README.md
lib/twterm/tweetbox.rb
twterm.gemspec

Updated `twitter-text` gem to v2.x to support the weighted length calculation.
https://developer.twitter.com/en/docs/developer-utilities/twitter-text.html

Support weighted length

---

lib/twterm/event/open_photo.rb
lib/twterm/photo_viewer.rb
lib/twterm/photo_viewer_backend/abstract_photo_viewer_backend.rb
lib/twterm/photo_viewer_backend/browser_backend.rb
lib/twterm/photo_viewer_backend/imgcat_backend.rb
lib/twterm/photo_viewer_backend/quick_look_backend.rb
lib/twterm/tab/status_tab.rb
lib/twterm/tab/user_tab.rb
lib/twterm/user.rb

Added "View profile image" menu to the user tab.

Preview icon

---

lib/twterm/tab/user_tab.rb
lib/twterm/user.rb

Added "View profile background image" menu to the user tab.

Profile background image

---

lib/twterm/tweetbox.rb

It allows you to create a thread without including your own `@screen_name`.
自分にリプライしてツイートを繋げるときは `@screen_name` を入れたくなかったので、プロンプトの一部じゃなくて初期入力にして消せるようにしてみました。

Make @screen_name editable on replying prompt

---

lib/twterm/environment.rb

Fix redirection order to hide error messages by `which` command.

Fix external command checks

---

lib/twterm/streaming_client.rb

Use proper name

---

Gemfile.lock
lib/twterm/version.rb

Bump version to v2.5.0

---

lib/twterm/tab/new/list.rb

Fix a bug where lists cannot be searched

---

.circleci/config.yml
Gemfile.lock
Makefile
README.md
gemset.nix
shell.nix

As this project requires several native extensions, it is convenient if we can set up development environment with `nix-shell`.

Introduce nix-shell for development

---

.gitignore
Makefile
README.md
default.nix
nix/Gemfile
nix/Gemfile.lock
nix/gemset.nix

Now `twterm` can be installed easily with Nix :tada:

Introduce Nix-based installation

---

lib/twterm/image/underlined.rb
lib/twterm/tab_manager.rb

Add underline to the current tab name

---

lib/twterm/tab/status_tab.rb

Closes #394
This change allow users to open conversation from a status tab.

Add "Show conversation" menu to Twterm::Tab::StatusTab

---

.circleci/config.yml
Gemfile.lock
gemset.nix
lib/twterm/key_mapper.rb
lib/twterm/persistable_configuration_proxy.rb
lib/twterm/preferences.rb
twterm.gemspec

Some dependencies are also updated for the sake of breaking changes and segfaults.

Test against Ruby 3.0

---

lib/twterm/image.rb

which should have been added in #406

Define Image#underlined method

---

.circleci/config.yml
Makefile

artifact: https://285-28815034-gh.circle-artifacts.com/0/doc/index.html

Add `docs` task to Makefile

---

lib/twterm/image_builder/user_name_image_builder.rb
lib/twterm/list.rb
lib/twterm/status.rb
lib/twterm/tab/abstract_tab.rb
lib/twterm/user.rb

Docs are essential for sustainable development.
This is a small but the very first step.

Add some documentation

---

lib/twterm/color_manager.rb
lib/twterm/message_window.rb
lib/twterm/screen.rb
lib/twterm/search_query_window.rb
lib/twterm/tweetbox.rb

It makes the code base harder to read

Avoid including Curses

---

lib/twterm/screen.rb
lib/twterm/tab_manager.rb

Open clicked tab

---

README.md
twterm.gemspec

Update CRuby requirement

---

Gemfile.lock
gemset.nix
lib/twterm/version.rb

Bump version to v2.9.0

---

lib/twterm/image/attr.rb
lib/twterm/image/bold.rb
lib/twterm/image/color.rb
lib/twterm/image/underlined.rb
spec/twterm/image/bold_spec.rb
spec/twterm/image/color_spec.rb

I hope this will contribute to performance improvement.

Fuse attributes when possible

---

lib/twterm/image.rb
lib/twterm/image/dim.rb
lib/twterm/tab/statuses/abstract_statuses_tab.rb
spec/twterm/image/dim_spec.rb

Making less important information more modest

Gray out date and retweeted-by

---

README.md

Made it more concise.
[Rendered](https://github.com/ryota-ka/twterm/blob/ebaa205ee75875b0fe46976fd85a03731cbfe142/README.md#installation)

Update "installation" section in README

---

README.md

[Rendered](https://github.com/ryota-ka/twterm/blob/3c9e45dd05f92d99c32dc39ba892c9f23e600831/README.md#installation)

Update Nix installation section in README

---

Gemfile
twterm.gemspec

https://github.com/rubygems/bundler/pull/7222

Move development dependencies from gemspec into Gemfile

---

README.md

Closes #443, thanks to @morishin.

Fix Nix installation instruction
